version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: starfish-backend
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/web/api/logs
    networks:
      - starfish-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: starfish-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - SERVER_BASE_URL=http://backend:8002  # For client-side
    networks:
      - starfish-network
    restart: unless-stopped

networks:
  starfish-network:
    driver: bridge

volumes:
  logs: 